#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_DIALOG1                             100
#define IDR_MENU1                               118
#define DIALOG_INSERIR                          120
#define IDD_DIALOG2                             122
#define IDD_DIALOG3                             126
#define IDD_DIALOG4                             128
#define IDD_DIALOG5                             129
#define IDD_DIALOG6                             130
#define IDD_DIALOG7                             131
#define IDD_DIALOG8                             132
#define ASSISTIR_1                              40000
#define ASSISTINDO_BOX                          40001
#define AUXILIAR_LABEL                          40002
#define EXPORTAR_CSV                            40003
#define LISTBOX_GENEROSMAIS                     40004
#define LISTBOX_MARATONAR                       40005
#define BOTAO_PESQUISAR_EXCLUIR                 40006
#define LISTBOX_ASSISTINDO                      40007
#define MENU_MARATONAR                          40008
#define TEMPORADAATUAL_EDITAR                   40009
#define ASSISTIR1EP                             40010
#define EPISODIOATUAL_EDITAR                    40011
#define EPISODIOS_INSERIR                       40012
#define MENU_GENEROS_ASSISTIDOS                 40013
#define CONFIRMARATUAL_HISTORICO                40014
#define EPISODIOATUAL_BOX                       40015
#define EPISODIOS_INSERIR_ALTERAR               40016
#define MENU_BURRO                              40017
#define LABEL_EXCLUIR                           40018
#define TEMPORADAATUAL_BOX                      40019
#define EPISODIOATUAL_TEXT                      40020
#define LISTBOX_ALTERAR                         40021
#define IDOK_ALTERAR                            40022
#define TEMPORADAATUAL_TEXT                     40023
#define FINALIZAR_BOTAO                         40024
#define LABEL_PESQUISAR                         40025
#define HISTORICO_BOX                           40026
#define LISTBOX_EXCLUIR                         40027
#define ASSISTINDO_HISTORICO_BOX                40028
#define AUXILIAR_LABEL_ALTERAR                  40029
#define BOTAO_PESUISAR_ALTERAR                  40030
#define HISTORICO_TEXT                          40031
#define NOME_ALTERAR                            40032
#define PESQUISARHISTORICO_BOX                  40033
#define CLASSIFICACAO_ALTERAR                   40034
#define PESQUISARHISTORICO                      40035
#define FILTRAR_COMBOBOX                        40036
#define PESQUISARHISTORICO_BOTAO                40037
#define TEMPORADAS_ALTERAR                      40038
#define BOTAO_EXCLUIR                           40039
#define REMOVERHISTORICO_BOTAO                  40040
#define LISTBOX_HISTORICO                       40041
#define PLATAFORMA_ALTERAR                      40042
#define DURACAO_ALTERAR                         40043
#define MENU_SERIES_ALTERAR                     40044
#define GENERO_ALTERAR                          40045
#define NOME_INSERIR                            40046
#define BOTAO_ALTERAR                           40047
#define MENU_SERIES_INSERIR                     40048
#define CONFIRMAR_ALTERAR                       40049
#define TITULO                                  40050
#define EPISODIOS_TREEVIEW                      40051
#define MENU_SERIES_EXCLUIR                     40052
#define TEMPORADAS_INSERIR                      40053
#define PLATAFORMA_INSERIR                      40054
#define TAB                                     40055
#define DURACAO_INSERIR                         40056
#define PESQUISAR_BOX                           40057
#define FILTRAR_BOX                             40058
#define GENERO_INSERIR                          40059
#define CONFIRMAR_BOTAO                         40060
#define SERIES_BOX                              40061
#define INSERIR_BOTAO                           40062
#define LISTBOX_SERIES                          40063
#define CLASSIFICACAO_INSERIR                   40064
#define INFORMACOES_BOX                         40065
#define NOME_BOX                                40066
#define TEMPORADAS_BOX                          40067
#define TOTALEPI_BOX                            40068
#define PLATAFORMA_BOX                          40069
#define CLASSIFICACAO_BOX                       40070
#define GENERO_BOX                              40071
#define DURACAO_BOX                             40072
#define NOME                                    40073
#define TEMPORADAS                              40074
#define TOTALEPI                                40075
#define PLATAFORMA                              40076
#define CLASSIFICACAO                           40077
#define GENERO                                  40078
#define DURACAO                                 40079
#define ASSISTIR_BOTAO                          40080
#define PESQUISAR                               40081
#define PESQUISAR_BOTAO                         40082
